apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-web-app
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: student-web-app
  template:
    metadata:
      labels:
        app: student-web-app
    spec:
      containers:
      - name: student-web-app
        image: harishtiru/student-web:${BUILD_ID}
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
