apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-web-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: student-web-app
  template:
    metadata:
      labels:
        app: student-web-app
    spec:
      containers:
      - name: student-web-app
        image: harishtiru/student-web:${BUILD_ID}
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: student-web-app
spec:
  selector:
    app: student-web-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000 # Choose any available port number between 30000 and 32767
  type: NodePort
